version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
    env_file: .env
  redis:
    image: redis
    volumes:
      - data:/var/lib/redis
    networks:
      - backend
    env_file: .env
  worker:
    image: app
    networks:
      - backend
    links:
      - redis
      - postgres
    env_file: .env
    command: rq worker -c rqworker
  web:
    image: app
    networks:
      - backend
    links:
      - redis
      - postgres
    ports:
      - 8000:8000
    env_file: .env
    command: uwsgi --ini uwsgi.ini
volumes:
  data: {}
networks:
  backend:
    driver: bridge
